Derive internal keys.
zcash/orchard pull request #270
Opened 2022-01-06 15:14 UTC by therealyingtong

As specified in https://github.com/zcash/zips/pull/576.

2022-01-22 17:32 UTC, daira commented on src/keys.rs
> +        CommitIvkRandomness(to_scalar(PrfExpand::OrchardRivkInternal.expand(&sk.0)))
This isn't correct. rivk<sub>internal</sub> is derived from ak, nk, and rivk of the external full viewing key, not directly from the spending key.

2022-01-22 17:35 UTC, daira commented on src/keys.rs
> +        let rivk_internal = CommitIvkRandomness::from_bytes(&rivk_internal)?;
This is incorrect too; it's missing a ToScalar<sup>Orchard</sup> call.

2022-01-22 17:37 UTC, daira requested changes
Please delete `InternalSpendingKey` and fix the rivk<sub>internal</sub> derivation to use ToScalar<sup>Orchard</sup>.

2022-02-02 00:37 UTC, str4d approved these changes
utACK. I verified that the test vectors match https://github.com/zcash-hackworks/zcash-test-vectors/blob/6c2bac7b73e345d311cffb044522fc453f40cd73/test-vectors/rust/orchard_key_components.rs

2022-02-02 16:36 UTC, nuttycom approved these changes
utACK

2022-02-03 00:34 UTC, daira approved these changes
utACK. I haven't checked that the test vectors match the generated ones.

2022-02-03 00:42 UTC, merged