Change license from BOSL to "MIT OR Apache-2.0"
zcash/orchard pull request #405
Opened 2023-12-19 20:39 UTC by daira

Per https://twitter.com/jswihart/status/1737192396150972544

2023-12-19 21:02 UTC, str4d requested changes

2023-12-19 21:02 UTC, str4d commented on COPYING.md
> +to the above "MIT OR Apache-2.0" dual license in release 0.6.1. The license
There are breaking changes already merged into the repo, so the next crate version will be 0.7.0:
```suggestion
to the above "MIT OR Apache-2.0" dual license in release 0.7.0. The license
```

2023-12-20 00:01 UTC, str4d approved these changes
ACK ac4b52187fb2748058ce27c3b574027a5836690e.

2023-12-20 00:03 UTC, merged

2023-12-20 00:44 UTC, daira commented
Follow-up issues/PRs:
* #407 to make an orchard release
* https://github.com/zcash/librustzcash/pull/1071 to remove BOSL licence references from librustzcash
* https://github.com/zcash/zcash/pull/6800 to remove BOSL licence references from zcashd (this might be done in https://github.com/zcash/zcash/pull/6784 instead).